// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sbvzjyqzbfpfkuecgfgr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNidnpqeXF6YmZwZmt1ZWNnZmdyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUzNTE5MDcsImV4cCI6MjA2MDkyNzkwN30.ToSfMoDMIJgiH0KqUglWaHcAAjb-nH6fT4wTFXSjMIs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);